name: PRODUCTION - CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: "14.15"

      - name: Build frontend
        run: |
          npm i
          npm run build

      - name: Copy frontend files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          port: ${{ secrets.PROD_PORT }}
          key: ${{ secrets.PROD_KEY }}
          rm: true
          strip_components: 3
          source: "./dist/src/"
          target: "~/app"